#version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Critical for data persistence
    ports:
      - "5432:5432"
      
volumes:
  postgres_data:  # Named volume declaration